### ISSUE TITLE
List of bugs in the Pulbisher and Redaction tools

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/safe-places#40]
There seem to be many bugs in these tools. Here is a list:

- [x] The drawing tools are covered by the redaction tool window. (see #41)
- [ ] There is an error (from google) about page not being able to load correctly, when either the API key OR the *Billing* is not valid or activated. This should be made more clear and presented to the user. For example, you can test for valid API key using code like that found in [my own map](https://github.com/E3V3A/MMM-FlightsAbove/blob/master/tools/MagicRadarBB.html). But we *also* need to test for Billing. (See #42 )
- [ ] There seem to be some code errors in the jquery according to FF/Chrome debuggers. (See #43)
- [ ] There are a many additional CSS errors... (#29)
- [x] Even after I manage to draw points and boxes, both: (#46)
  (a) - the time sliders and 
  (b) - the save button is always grayed out!? Why is that? 

- [x] The map **always** start in Boston. I'm not in Boston, so where do I change this default?
- [ ] In Brave (a Chrome mod) there's only a blank white page... (#39)

**Comment by penrods** [comment]
MIT is in Boston...  This is a common kind of "Nod" to the developers.  Zoom with no data loaded also takes you to Kansas City.  This isn't a bug, IMHO.

In case you didn't notice, once you load a .json file it auto-zooms to the extents of that file.

**Comment by E3V3A** [comment]
I was not able to import anything... 
#45

**Comment by kenpugsley** [comment]
Just checking ... are you working trying off the `develop` branch or `master`?  `develop` is now a few changes behind - the `master` branch is the correct one to use at the moment I believe.

**Comment by rx** [comment]
@penrods I would be helpful to get the develop branch up to date with master, so this setup impedance goes away. I'm assuming the goal is to use a GitFlow workflow the same as the safe-paths repo.
