### ISSUE TITLE
Safe places Roadmap [draft]

### ISSUE THREAD

**Issue by Utzel-Butzel** [tripleblindmarket/safe-places#47]
Ideas up for discussion

### Technical requirements:
- the application itself should be server independent (just html & js) cc: @penrods 
- health organizations can host the application on there own (actually, they can just download the application and use it locally) cc: @penrods 
- simple modifications should be possible using a standardized/common tecstack cc: @penrods 
- the use of APIs like Google Places API, or the Safe Path API should be optional (saving, editing, etc. should work without an API and local files)

### Technical actions:
- [ ] start using a frontend framework (react.js & redux)
- [ ] Unifying `location scrubber (reduction tool)`, `publisher` and `path creator` into a single PWA

### Backend
- [ ] enable downloading clustered case download (the app will send it's path boundaries to the server and only receives data for this area)
- [ ] having a sample implementation of a API

### Version 0.1-alpha

- Create branch for react implementation @kyletowle 
- Have all the current features in place with a nice UX and a solid technical foundation

### Version x.x-beta

- Implement feature requests and ideas from health officials
- having the API implementation
